# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqg3SgqCQ_if8P-vBbAPTxDPp1EE4VPi
"""

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt

(X_Train, Y_Train), (X_Test, Y_Test) = mnist.load_data()

plt.figure(figsize=(5, 5))
for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(X_Train[i], cmap='gray')
    plt.title(f"Label: {Y_Train[i]}")
    plt.axis('off')
plt.show()

import tensorflow as tf

X_Train = X_Train.astype('float32') / 255.0
X_Test = X_Test.astype('float32') / 255.0
X_Train = X_Train[..., tf.newaxis]  # צורת קלט (28, 28, 1)
X_Test = X_Test[..., tf.newaxis]

print(f"Training data shape: {X_Train.shape}")
print(f"Training labels shape: {Y_Train.shape}")
print(f"Test data shape: {X_Test.shape}")

from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')  # 10 digits (0-9)
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',  # or 'categorical_crossentropy' if using one-hot
    metrics=['accuracy']
)

# View the architecture
model.summary()

history = model.fit(
    X_Train, Y_Train,
    epochs=5,  # Start with 5 epochs, increase if needed
    batch_size=32,
    validation_split=0.1,  # Use 10% of training data for validation
    verbose=1
)

test_loss, test_acc = model.evaluate(X_Test, Y_Test)
print("Accuracy on test set:", test_acc)

model.save('/content/drive/MyDrive/מספרים/model.h5')

from PIL import Image
import numpy as np
import cv2

img_url = "/content/drive/MyDrive/מספרים/8.png"

img = cv2.imread(img_url, cv2.IMREAD_GRAYSCALE)

plt.imshow(img, cmap='gray')
plt.title("Gray Image")
plt.axis('off')
plt.show()

img_resized = cv2.resize(img, (28, 28))

img_inverted = 255 - img_resized

img_normalized = img_inverted / 255.0

img_input = img_normalized.reshape(1, 28, 28, 1)

prediction = model.predict(img_input)
predicted_digit = np.argmax(prediction)

plt.imshow(img_normalized, cmap='gray')
plt.title(f"Predicted digit: {predicted_digit}")
plt.axis('off')
plt.show()

"""עם פעולות חיבור חיסור וכפל"""

from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers, models

# =====================
# 1. הגדרת קבצים עבור חיבור
# =====================
file_paths = [
    "/content/drive/MyDrive/מספרים/חיבור.png",
    "/content/drive/MyDrive/מספרים/חיבור2.png",
    "/content/drive/MyDrive/מספרים/חיבור3.png",
    "/content/drive/MyDrive/מספרים/פלוס10.png",
    "/content/drive/MyDrive/מספרים/פלוס11.png",
    "/content/drive/MyDrive/מספרים/פלוס5.png",
    "/content/drive/MyDrive/מספרים/פלוס6.png",
    "/content/drive/MyDrive/מספרים/פלוס8.png",
    "/content/drive/MyDrive/מספרים/פלוס9.png",
    "/content/drive/MyDrive/מספרים/פלוס11.png"
]

copies_per_image = 120
X_plus = []
y_plus = []

for path in file_paths:
    for _ in range(copies_per_image):
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            print(f"לא הצליח לקרוא את התמונה: {path}")
            continue
        img = cv2.resize(img, (28,28))
        img = 255 - img
        img = img / 255.0
        X_plus.append(img.reshape(28,28,1))
        y_plus.append(10)  # תווית חיבור

X_plus = np.array(X_plus)
y_plus = np.array(y_plus)

# חלוקה לאימון ובדיקה עבור החיבור
X_plus_train, X_plus_test, y_plus_train, y_plus_test = train_test_split(
    X_plus, y_plus, test_size=0.2, random_state=42
)

# =====================
# 2. טעינת MNIST
# =====================
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1,28,28,1)/255.0
x_test  = x_test.reshape(-1,28,28,1)/255.0

# =====================
# 3. איחוד כל הנתונים
# =====================
X_train = np.concatenate((x_train, X_plus_train), axis=0)
y_train = np.concatenate((y_train, y_plus_train), axis=0)

X_test = np.concatenate((x_test, X_plus_test), axis=0)
y_test = np.concatenate((y_test, y_plus_test), axis=0)

print("צורת מאגר האימון:", X_train.shape, y_train.shape)
print("צורת מאגר הבדיקה:", X_test.shape, y_test.shape)

from sklearn.utils import shuffle

# ערבוב מאגרי האימון
X_train, y_train = shuffle(X_train, y_train, random_state=42)

# ערבוב מאגרי הבדיקה (אופציונלי)
X_test, y_test = shuffle(X_test, y_test, random_state=42)

X_train, y_train = shuffle(X_train, y_train, random_state=42)

# ערבוב מאגרי הבדיקה (אופציונלי)
X_test, y_test = shuffle(X_test, y_test, random_state=42)

plt.figure(figsize=(8, 8))
for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(X_train[i], cmap='gray')
    plt.title(f"Label: {y_train[i]}")
    plt.axis('off')
plt.show()

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(11, activation='softmax')  # 0-9 ספרות + חיבור
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

# =====================
# 5. אימון המודל
# =====================
history = model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

test_img_path = "/content/drive/MyDrive/מספרים/חיבור.png"

img = cv2.imread(test_img_path, cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (28,28))
img = 255 - img
img = img / 255.0
img_input = img.reshape(1,28,28,1)

prediction = model.predict(img_input)
predicted_label = np.argmax(prediction)

plt.imshow(img, cmap='gray')
plt.title(f"Predicted label: {predicted_label}")
plt.axis('off')
plt.show()

model.save('/content/drive/MyDrive/מספרים/model_with_plus.h5')

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from tensorflow.keras import layers, models

# =====================
# 1. הגדרת קבצים ותוויות
# =====================
# המפתח הוא שם הפעולה, הערך הוא רשימת קבצים + התווית שלה
symbol_files = {
    "חיבור": {
        "paths":[
    "/content/drive/MyDrive/מספרים/חיבור.png",
    "/content/drive/MyDrive/מספרים/חיבור2.png",
    "/content/drive/MyDrive/מספרים/חיבור3.png",
    "/content/drive/MyDrive/מספרים/פלוס10.png",
    "/content/drive/MyDrive/מספרים/פלוס11.png",
    "/content/drive/MyDrive/מספרים/פלוס5.png",
    "/content/drive/MyDrive/מספרים/פלוס6.png",
    "/content/drive/MyDrive/מספרים/פלוס8.png",
    "/content/drive/MyDrive/מספרים/פלוס9.png",
    "/content/drive/MyDrive/מספרים/פלוס11.png"
    ],
        "label": 10  # תווית חיבור
    },
    "שווה": {
        "paths": [
            "/content/drive/MyDrive/מספרים/1שווה.png",
            "/content/drive/MyDrive/מספרים/שווה 2.png",
            "/content/drive/MyDrive/מספרים/שווה 3.png",
            "/content/drive/MyDrive/מספרים/שווה 7.png",
            "/content/drive/MyDrive/מספרים/שווה 7.png",
            "/content/drive/MyDrive/מספרים/שווה 8.png",
            "/content/drive/MyDrive/מספרים/שווה 9.png",
            "/content/drive/MyDrive/מספרים/שווה4.png",
            "/content/drive/MyDrive/מספרים/שווה5.png",
            "/content/drive/MyDrive/מספרים/שווה9.png"
        ],
        "label": 11  # תווית שווה
    }
}

copies_per_image = 100
X_symbols = []
y_symbols = []

# טעינת כל הקבצים לכל סוג
for symbol, info in symbol_files.items():
    for path in info["paths"]:
        for _ in range(copies_per_image):
            img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
            if img is None:
                print(f"❌ לא הצלחתי לקרוא את התמונה: {path}")
                continue
            img = cv2.resize(img, (28,28))
            img = 255 - img  # הפיכת צבעים אם הרקע לבן
            img = img / 255.0
            X_symbols.append(img.reshape(28,28,1))
            y_symbols.append(info["label"])

X_symbols = np.array(X_symbols)
y_symbols = np.array(y_symbols)

# חלוקה לאימון ובדיקה
X_sym_train, X_sym_test, y_sym_train, y_sym_test = train_test_split(
    X_symbols, y_symbols, test_size=0.2, random_state=42
)

# =====================
# 2. טעינת MNIST
# =====================
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1,28,28,1)/255.0
x_test  = x_test.reshape(-1,28,28,1)/255.0

# =====================
# 3. איחוד כל הנתונים
# =====================
X_train = np.concatenate((x_train, X_sym_train), axis=0)
y_train = np.concatenate((y_train, y_sym_train), axis=0)

X_test = np.concatenate((x_test, X_sym_test), axis=0)
y_test = np.concatenate((y_test, y_sym_test), axis=0)

print("📦 מאגר אימון:", X_train.shape, y_train.shape)
print("📦 מאגר בדיקה:", X_test.shape, y_test.shape)

# ערבוב
X_train, y_train = shuffle(X_train, y_train, random_state=42)
X_test, y_test = shuffle(X_test, y_test, random_state=42)

X_train, y_train = shuffle(X_train, y_train, random_state=42)

# ערבוב מאגרי הבדיקה (אופציונלי)
X_test, y_test = shuffle(X_test, y_test, random_state=42)

plt.figure(figsize=(8, 8))
for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(X_train[i], cmap='gray')
    plt.title(f"Label: {y_train[i]}")
    plt.axis('off')
plt.show()

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(12, activation='softmax')  # 0-9 ספרות + חיבור
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

# =====================
# 5. אימון המודל
# =====================
history = model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

test_img_path = "/content/drive/MyDrive/מספרים/בחינה png.png"

img = cv2.imread(test_img_path, cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (28,28))
img = 255 - img
img = img / 255.0
img_input = img.reshape(1,28,28,1)

prediction = model.predict(img_input)
predicted_label = np.argmax(prediction)

plt.imshow(img, cmap='gray')
plt.title(f"Predicted label: {predicted_label}")
plt.axis('off')
plt.show()

model.save('/content/drive/MyDrive/מספרים/modell2.h5')